# Diffuser params
name: diffuser_hisdit
history_model: encoder # encoder  # translator
time_proj_dim: 64
time_embed_dim: 64
freq_shift: 0
flip_sin_to_cos: True
num_train_timesteps: 100
num_inference_timesteps: 100
history_len: 1
history_dim: 128
batch_norm: False
