name: trajectory
data_dir: ${oc.env:HOME}/datasets/partnet-mobility

dataset: umpnet
model: trajectory
# batch_size: 64
batch_size: 32
lr: 1e-3
mask_input_channel: True
randomize_camera: True
seed: 42
n_points: 1200
