name: synthetic_diffuser_pn++
lr: 1e-4
# lr_warmup_steps: 100
# batch_size: 64
# epochs: 5000
# train_sample_number : 50300
check_val_every_n_epoch: 5
trajectory_len: 1
mode: delta

lr_warmup_steps: 5
batch_size: 1
epochs: 10000  # For toy
train_sample_number : 2  # For toy
