name: trajectory_artflownet
lr: 1e-3
batch_size: 64
epochs: 200
check_val_every_n_epoch: 1
trajectory_len: 1
mode: "delta"
# mask_input_channel: True
mask_input_channel: False

# batch_size: 32


# Toy dataset
# batch_size: 1
# mask_input_channel: False
# trajectory_len: 1
# epochs: 500
