name: trajectory_diffuser
lr: 1e-4
batch_size: 64
epochs: 200
check_val_every_n_epoch: 1
trajectory_len: 1
mode: "delta"
mask_input_channel: False

# Diffuser params
in_channels: 3
time_proj_dim: 64
time_embed_dim: 64
freq_shift: 0
flip_sin_to_cos: True
num_train_timesteps: 500
