mode: eval

# This is somewhat arbitrary.
job_type: ${mode}_${dataset.name}_wta

defaults:
  # Each of these have their own configuration parameters.
  # - dataset: flowbot
  - dataset: trajectory
  - model: artflownet
  # - model: diffuser

  # A set of inference settings for the model. Note that these may be different
  # from / or a subset of the training settings. This is that we don't have to
  # provide, like, a learning rater or something to eval.
  - inference: ${dataset}_${model}

  # Simple shared imports.
  - _logging

  # Override.
  - _self_

seed: 42

# This is the checkpoint that we're evaluating. You can change this to whatever you need,
# like if you want multiple checkpoints simultaneously, etc.
checkpoint:
  # If we want to load a model for a specific run, we can change that here.
  # run_id: ???

  # ArtflowNet:
  # run_id: nxe7uxh4  # flowbot
  # run_id: ah26pym3  # traj 1
  # run_id: l5stf32k  # traj 5
  # run_id: m2twtvm7   # traj 10
  # run_id: yiel0na4   # traj 15
  # run_id: zmnrssob  # traj 20

  # Diffuser:
  # run_id: 5pp284n8  # traj1
  # run_id: aww6u0ye  # traj5
  # run_id: f2abrctk  # traj10

  # Flowbot no mask
  # run_id: 4xb2c95k

  # Flowbot half-half
  # run_id: 302dfxe5
  # Flowbot fully closed
  run_id: 8699d8oe
  # run_id: nxe7uxh4  # flowbot
  # run_id: ah26pym3  # traj 1
  # run_id: l5stf32k  # traj 5
  # run_id: ljpdwcna  # traj 7
  # run_id: m2twtvm7   # traj 10
  # run_id: yiel0na4   # traj 15
  # run_id: zmnrssob  # traj 20
  reference: ${wandb.entity}/${wandb.project}/model-${checkpoint.run_id}:best

resources:
  num_workers: 30
  n_proc_per_worker: 2
  gpus:
    - 0

wandb:
  # The group ***should*** be the same as the training group (so it can be bundled)
  # nicely in the UI. But you might have a one-off eval or something.
  # group: ???
  # group: flowbot  # flowbot
  # group: traj1  # traj 1 experiment-sb009k1f
  # group: traj5  # traj 5 experiment-y2kdp0hq
  # group: traj1
  # group: diffuser1
  # group: flowbot_nomask
  # group: flowbot_mixed
  group: flowbot_closed
  # reference: /home/yishu/open_anything_diffusion/logs/train_trajectory/2023-09-14/00-11-03/checkpoints/epoch=3819-step=3002520.ckpt  # diffuser1
  # group: traj7  # traj 5 experiment-y2kdp0hq
  # group: traj1

metric_output_dir: './logs'
